services:
  - type: web
    name: hrms-lite-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -m uvicorn app.main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: DB_NAME
        value: hrms_lite
